import { Metadata } from "next";
import Modal from "@/components/Modal";
import "./globals.css";

export const metadata: Metadata = {
  title: "Trello clone",
  description: "Generated by Yassir",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        {children} <Modal />
      </body>
    </html>
  );
}
